version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:15.11.0
    working_directory: ~/voter-dapp
    resource_class: medium+
    steps:
      - checkout
      - run:
          name: Run build
          command: |
            yarn
            yarn build
      - save_cache:
          key: voter-dapp-build-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/voter-dapp
  test:
    docker:
      - image: circleci/node:lts
    working_directory: ~/voter-dapp
    steps:
      - restore_cache:
          key: voter-dapp-build-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Run tests
          command: yarn test --watchAll=false

  deploy:
    docker:
      - image: circleci/node:lts
    steps:
      - run:
          name: Run deploy
          command: |
            curl -X POST \
            https://api.vercel.com/v1/integrations/deploy/{{ .Environment.VERCEL_HOOK }}

workflows:
  version: 2.1
  voter-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          context: voter-dapp
          requires:
            - build
            - test
          filters:
            branches:
              only: master
