version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:15.10.0
    working_directory: ~/voter-dapp
    steps:
      - checkout
      - run:
          name: Run build
          command: yarn self-update && yarn -v && yarn && yarn build
      - save_cache:
          key: voter-dapp-build-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/voter-dapp
  test:
    docker:
      - image: circleci/node:lts
    working_directory: ~/voter-dapp
    steps:
      - restore_cache:
          key: voter-dapp-build-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Run tests
          command: yarn test --watchAll=false


workflows:
  version: 2.1
  voter-test:
    jobs:
      - build
      - test:
          requires:
            - build
